apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: rrodriperezz/${APP_NAME}:${APP_VERSION}
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: production